// <auto-generated />
using System;
using GymAppFresh.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymAppFresh.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250910133518_Chat_MessagingV2")]
    partial class Chat_MessagingV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymAppFresh.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("GymAppFresh.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ClientGuid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReadByMember")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadByStaff")
                        .HasColumnType("bit");

                    b.Property<int>("SenderType")
                        .HasColumnType("int");

                    b.Property<int>("ThreadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId", "CreatedAt");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("GymAppFresh.Models.ChatThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("GymLocationId")
                        .HasColumnType("int");

                    b.Property<int>("GymStaffId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("GymLocationId", "MemberId", "GymStaffId")
                        .IsUnique();

                    b.ToTable("ChatThreads");
                });

            modelBuilder.Entity("GymAppFresh.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CityId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("GymAppFresh.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("StudentCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("GymAppFresh.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("CoachName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentStudents")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CoachId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("GymAppFresh.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("MemberId", "CourseId")
                        .IsUnique();

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("GymAppFresh.Models.GymImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GymLocationId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("GymLocationId");

                    b.ToTable("GymImages");
                });

            modelBuilder.Entity("GymAppFresh.Models.GymLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("time");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("WCloseTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("WOpenTime")
                        .HasColumnType("time");

                    b.Property<int>("currentMember")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("GymLocations");
                });

            modelBuilder.Entity("GymAppFresh.Models.GymStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GymLocationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("ShiftEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("ShiftStart")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("GymLocationId");

                    b.HasIndex("MemberId");

                    b.HasIndex("RoleId");

                    b.ToTable("GymStaffs");
                });

            modelBuilder.Entity("GymAppFresh.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FitnessGoal")
                        .HasColumnType("int");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("GymLocationId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnboardingCompleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("daysPerWeek")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GymLocationId");

                    b.HasIndex("MembershipId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("GymAppFresh.Models.Membership", b =>
                {
                    b.Property<int>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembershipId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PacketType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MembershipId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("GymAppFresh.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GymAppFresh.Models.StaffAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("GymStaffId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GymStaffId");

                    b.HasIndex("MemberId");

                    b.ToTable("StaffAppointments");
                });

            modelBuilder.Entity("GymAppFresh.Models.StaffTimeOff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<TimeSpan?>("End")
                        .HasColumnType("time");

                    b.Property<int>("GymStaffId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("Start")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("GymStaffId");

                    b.ToTable("StaffTimeOffs");
                });

            modelBuilder.Entity("GymAppFresh.Models.StaffWorkRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("time");

                    b.Property<int>("GymStaffId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("GymStaffId", "DayOfWeek", "Start", "End")
                        .IsUnique();

                    b.ToTable("StaffWorkRules");
                });

            modelBuilder.Entity("WorkoutProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DaysPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Goal")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Split")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPrograms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "FATLOSS_BEG_3D",
                            DaysPerWeek = 3,
                            Description = "Full body + LISS (30-40dk).",
                            Equipment = "Bodyweight,Dumbbell",
                            Goal = 1,
                            Level = "Beginner",
                            Split = "FullBody",
                            Title = "Yağ Yakım – Başlangıç (3 gün)"
                        },
                        new
                        {
                            Id = 2,
                            Code = "HYPER_UL_4D",
                            DaysPerWeek = 4,
                            Description = "Progressive overload odaklı.",
                            Equipment = "Dumbbell,Barbell,Machines",
                            Goal = 5,
                            Level = "Beginner",
                            Split = "UpperLower",
                            Title = "Kas Geliştirme – Upper/Lower (4 gün)"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ENDUR_FB_3D",
                            DaysPerWeek = 3,
                            Description = "Düşük-orta yoğunluk, nefes ve tempo.",
                            Equipment = "Bodyweight",
                            Goal = 6,
                            Level = "Beginner",
                            Split = "FullBody",
                            Title = "Kondisyon – Full Body (3 gün)"
                        });
                });

            modelBuilder.Entity("GymAppFresh.Models.ChatMessage", b =>
                {
                    b.HasOne("GymAppFresh.Models.ChatThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("GymAppFresh.Models.Coach", b =>
                {
                    b.HasOne("GymAppFresh.Models.Category", "Category")
                        .WithMany("Coaches")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GymAppFresh.Models.Course", b =>
                {
                    b.HasOne("GymAppFresh.Models.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymAppFresh.Models.Coach", "Coach")
                        .WithMany("Courses")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("GymAppFresh.Models.Enrollment", b =>
                {
                    b.HasOne("GymAppFresh.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymAppFresh.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymAppFresh.Models.GymImage", b =>
                {
                    b.HasOne("GymAppFresh.Models.GymLocation", "GymLocation")
                        .WithMany("GymImages")
                        .HasForeignKey("GymLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GymLocation");
                });

            modelBuilder.Entity("GymAppFresh.Models.GymLocation", b =>
                {
                    b.HasOne("GymAppFresh.Models.City", "City")
                        .WithMany("Gyms")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("GymAppFresh.Models.GymStaff", b =>
                {
                    b.HasOne("GymAppFresh.Models.GymLocation", "GymLocation")
                        .WithMany("GymStaffs")
                        .HasForeignKey("GymLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymAppFresh.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GymAppFresh.Models.Role", "Role")
                        .WithMany("GymStaffs")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GymLocation");

                    b.Navigation("Member");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GymAppFresh.Models.Member", b =>
                {
                    b.HasOne("GymAppFresh.Models.GymLocation", "GymLocation")
                        .WithMany("Members")
                        .HasForeignKey("GymLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GymAppFresh.Models.Membership", "Membership")
                        .WithMany("Members")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GymLocation");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("GymAppFresh.Models.StaffAppointment", b =>
                {
                    b.HasOne("GymAppFresh.Models.GymStaff", "GymStaff")
                        .WithMany("StaffAppointments")
                        .HasForeignKey("GymStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymAppFresh.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GymStaff");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymAppFresh.Models.StaffTimeOff", b =>
                {
                    b.HasOne("GymAppFresh.Models.GymStaff", "GymStaff")
                        .WithMany("StaffTimeOffs")
                        .HasForeignKey("GymStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GymStaff");
                });

            modelBuilder.Entity("GymAppFresh.Models.StaffWorkRule", b =>
                {
                    b.HasOne("GymAppFresh.Models.GymStaff", "GymStaff")
                        .WithMany("StaffWorkRules")
                        .HasForeignKey("GymStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GymStaff");
                });

            modelBuilder.Entity("GymAppFresh.Models.Category", b =>
                {
                    b.Navigation("Coaches");

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("GymAppFresh.Models.ChatThread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("GymAppFresh.Models.City", b =>
                {
                    b.Navigation("Gyms");
                });

            modelBuilder.Entity("GymAppFresh.Models.Coach", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("GymAppFresh.Models.GymLocation", b =>
                {
                    b.Navigation("GymImages");

                    b.Navigation("GymStaffs");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("GymAppFresh.Models.GymStaff", b =>
                {
                    b.Navigation("StaffAppointments");

                    b.Navigation("StaffTimeOffs");

                    b.Navigation("StaffWorkRules");
                });

            modelBuilder.Entity("GymAppFresh.Models.Membership", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("GymAppFresh.Models.Role", b =>
                {
                    b.Navigation("GymStaffs");
                });
#pragma warning restore 612, 618
        }
    }
}
